# Docker Compose file for easier build and test in local machine
version: "3.8"
services:
  flask_app:
    container_name: contractor_portal
    build: ./flask_app
    ports:
      - 5000:5000
    environment:
      - MERAKI_API_KEY=${MERAKI_API_KEY}
    volumes:
      - ./flask_app:/app
    restart: "always"
